[functions]
  included_files = [
  "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/amp-context*",
  "node_modules/next/dist/server/future/route-modules/pages/vendored/contexts/head-manager-context*",
]

[build]
command = "npm run build && npm run export"
publish = "out"